### ISSUE TITLE
error trying to connect: Connection refused (os error 111)

### ISSUE THREAD

**Issue by h3ndrk** [jasonwhite/rudolfs#12]
Hi, thanks for the LFS server!

I'm trying to get the minimal docker-compose with Minio up but do not succeed:

```
_______@_______ ~/Documents/rudolfs » docker-compose up
Recreating lfs_rudolfs_1 ... done
Starting lfs_minio_1     ... done
Attaching to lfs_minio_1, lfs_rudolfs_1
rudolfs_1  |  2020-02-11T11:08:52.884 INFO  rudolfs > Initializing storage...
rudolfs_1  |  2020-02-11T11:08:52.886 ERROR rudolfs > error trying to connect: Connection refused (os error 111)
lfs_rudolfs_1 exited with code 1
minio_1    | Endpoint:  http://172.22.0.2:9000  http://127.0.0.1:9000
minio_1    | 
minio_1    | Browser Access:
minio_1    |    http://172.22.0.2:9000  http://127.0.0.1:9000
minio_1    | 
minio_1    | Object API (Amazon S3 compatible):
minio_1    |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
minio_1    |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
minio_1    |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
minio_1    |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
minio_1    |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
lfs_rudolfs_1 exited with code 1
lfs_rudolfs_1 exited with code 1
lfs_rudolfs_1 exited with code 1
lfs_rudolfs_1 exited with code 1
lfs_rudolfs_1 exited with code 1
lfs_rudolfs_1 exited with code 1
lfs_rudolfs_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping lfs_rudolfs_1   ... done
Stopping lfs_minio_1     ... done
```

I can successfully connect to Minio via `http://localhost:9000` but the rudolfs-container is in a restart loop. Also you can see in the `docker-compose.yml` below, I added a test container (then `docker-compose exec test /bin/ash`) from which I am able to ping and curl the Minio service.

#### `.env` (temporary secrets)

```
AWS_ACCESS_KEY_ID=kG5jGQs8jmPM6kQQeuEV
AWS_SECRET_ACCESS_KEY=j6DhdwWUEnNuxv22kBS79WV3dAej9LrVF7S3sRga
AWS_DEFAULT_REGION=us-west-1
LFS_ENCRYPTION_KEY=3f083affa058951a17e7ddecc994d9bc5bf07d7b05b6803d806284eee4d7ca0d
LFS_S3_BUCKET=test
LFS_MAX_CACHE_SIZE=10GB
```

#### `docker-compose.yml`

Changes: Remove `links` because it is deprecated. Remove other networks s.t. hopefully the default network gets used only.

```yaml
version: "3"
services:
  minio:
    image: minio/minio:latest
    ports:
    - "9000:9000"
    volumes:
    - miniodata:/data
    environment:
      # force using given key-secret instead of creating at start
    - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
    - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    command: ["server", "/data"]
    # networks:
    # - backend
  # test:
  #   image: alpine:latest
  #   command: ["ash", "-c", "while true; do sleep 3600; done"]
  #   # networks:
  #   # - backend
  rudolfs:
    image: jasonwhite0/rudolfs:latest
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
    - data:/data
    restart: always
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - LFS_ENCRYPTION_KEY=${LFS_ENCRYPTION_KEY}
    - LFS_S3_BUCKET=${LFS_S3_BUCKET}
    - LFS_MAX_CACHE_SIZE=${LFS_MAX_CACHE_SIZE}
    - AWS_S3_ENDPOINT=http://minio:9000
    entrypoint:
    - /tini
    - --
    - /rudolfs
    - --cache-dir
    - /data
    - --key
    - ${LFS_ENCRYPTION_KEY}
    - --s3-bucket
    - ${LFS_S3_BUCKET}
    - --max-cache-size
    - ${LFS_MAX_CACHE_SIZE}
    # networks:
    # - backend
  # A real production server should use nginx. How to configure this depends on
  # your needs. Use your Google-search skills to configure this correctly.
  #
  # nginx:
  #   image: nginx:stable
  #   ports:
  #   - 80:80
  #   - 443:443
  #   volumes:
  #   - ./nginx.conf:/etc/nginx/nginx.conf
  #   - ./nginx/errors.log:/etc/nginx/errors.log

volumes:
  data:
  miniodata:
# networks:
#   backend:
```
