### ISSUE TITLE
Trouble getting it to connect to S3

### ISSUE THREAD

**Issue by benthillerkus** [jasonwhite/rudolfs#76]
Hey, I've been pulling my hair out the last two days getting this thing to work, but I can never get beyond the initial `HeadBucket` test.
My setup is a minio server behind an nginx reverse proxy, and I'm not 100% sure, but nginx seems to be related to the issue.
I've been using mitmproxy and Wireshark and the nginx access logs to try to debug the problem and I think (part of) the issue is that with http2 both the `:authority` field and the `Host` header are being set; which might be a bug in rusoto or the version of hyper used(?).
But I'm not even sure that's the only problem either.

I know that I should be able to connect to the bucket with the `AWS_ACCESS_KEY_ID` + secret I provided, because I can use the REST API and WinSCP as a client.

It's all very hard to debug too, because even with `RUST_LOG=trace` I get no real indication of what I've actually send and what the server response was.

Do you know if the combination NGINX +  Minio should work?

**Comment by Pichas** [comment]
I spent a lot of time configuring this pair, here is my setup. I use url.com as example and all my services are behind the nginx reverse proxy and mapped to the 3 lvl url address with wildcart *.url.com cert. Be sure you use https, because http2 may not work without certs.


rudold .env file next to docker compose file
```env
AWS_ACCESS_KEY_ID=minio_admin
AWS_SECRET_ACCESS_KEY=minio_password
AWS_DEFAULT_REGION=us-east-1
LFS_ENCRYPTION_KEY=key_from_instruction
LFS_S3_BUCKET=lfs # any name you want
LFS_MAX_CACHE_SIZE=1GB
```

rudolf docker compose
```yaml
name: "rudolfs"
services:
  lfs:
    image: jasonwhite0/rudolfs:latest
    ports:
      - 8087:8087
    volumes:
      - rudolf:/data
    restart: always
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - LFS_ENCRYPTION_KEY
      - LFS_S3_BUCKET
      - LFS_MAX_CACHE_SIZE
      - AWS_S3_ENDPOINT=https://s3.url.com
    entrypoint:
      - /tini
      - --
      - /rudolfs
      - --port
      - "8087"
      - --cache-dir
      - /data
      - --key
      - ${LFS_ENCRYPTION_KEY}
      - --max-cache-size
      - ${LFS_MAX_CACHE_SIZE}
      - s3
      - --bucket
      - ${LFS_S3_BUCKET}

volumes:
  rudolf:
```


minio docker compose
```yaml
name: minio
services:
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: always
    ports:
      - 8083:9600
      - 8084:9601
    volumes:
      - config:/root/.minio
      - export:/export
    environment:
      - MINIO_SERVER_URL=https://s3.url.com/ui/
      - MINIO_BROWSER_REDIRECT_URL=https://s3.url.com/ui/
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_password
    command: server /export --address :9600 --console-address :9601

volumes:
  export:
    driver: local
  config:
    driver: local
```

nginx part

rudolfs
```conf
server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name lfs.url.com;
        ssl_certificate /etc/letsencrypt/rsa-certs/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/rsa-certs/privkey.pem;
        ssl_certificate /etc/letsencrypt/ecc-certs/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/ecc-certs/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/ecc-certs/chain.pem;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_protocols TLSv1.3 TLSv1.2;
        ssl_ciphers 'TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384';
        ssl_ecdh_curve X448:secp521r1:secp384r1;
        ssl_prefer_server_ciphers on;
        ssl_stapling on;
        ssl_stapling_verify on;
        client_max_body_size 0;

        http2 on;
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;

                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade $http_upgrade;
                proxy_http_version 1.1;

                resolver 127.0.0.11;
                proxy_pass http://localhost:8087;
                proxy_redirect off;

                proxy_set_header Connection "";
                chunked_transfer_encoding off;
                proxy_connect_timeout 300;

        }
}
```

minio
```conf
server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name s3.url.com;
        ssl_certificate /etc/letsencrypt/rsa-certs/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/rsa-certs/privkey.pem;
        ssl_certificate /etc/letsencrypt/ecc-certs/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/ecc-certs/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/ecc-certs/chain.pem;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_protocols TLSv1.3 TLSv1.2;
        ssl_ciphers 'TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384';
        ssl_ecdh_curve X448:secp521r1:secp384r1;
        ssl_prefer_server_ciphers on;
        ssl_stapling on;
        ssl_stapling_verify on;
        client_max_body_size 0;

        http2 on;
        proxy_buffering off;
        proxy_request_buffering off;

        location ~ ^/ui/(?<pt>.*) {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;

                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;

                resolver 127.0.0.11;
                proxy_pass http://localhost:8084;
                rewrite ^ /$pt break;
                proxy_redirect off;
        }

        location ~ ^/(?<pt>.*) {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;

                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade $http_upgrade;
                proxy_http_version 1.1;

                resolver 127.0.0.11;
                proxy_pass http://localhost:8083;
                rewrite ^ /$pt break;
                proxy_redirect off;

                proxy_set_header Connection "";
                chunked_transfer_encoding off;
                proxy_connect_timeout 300;

        }
}
```
